### ISSUE TITLE
What it this ... ?

### ISSUE THREAD

**Issue by flatmax** [madChopsCoderAu/wat2#5]

**Comment by alexhayes** [comment]
This should be closed as a duplicate of #1

**Comment by alexhayes** [comment]
So perhaps you can close it then @flatmax if you think it's worthy of closing, since we aren't able to close issues.

![image](https://user-images.githubusercontent.com/142916/34744537-a58f906a-f5e1-11e7-85ed-99a23d36e741.png)

**Comment by flatmax** [comment]
how do we give everyone the right to close issues ... it this a github issue ?

**Comment by neerolyte** [comment]
I love that you think you know enough about GitHub to start a social network on it, but haven't got the slightest inkling of how the permissions work.

**Comment by neerolyte** [comment]
[RTFM?](http://lmgtfy.com/?q=github+permissions)

**Comment by flatmax** [comment]
I've changed the default permissions for repos to admin ... that way when someone creates a repo, the defaults make them under everyone's control.

**Comment by flatmax** [comment]
As per @alexhayes request
